// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PasabuyAPI.Data;

#nullable disable

namespace PasabuyAPI.Migrations
{
    [DbContext(typeof(PasabuyDbContext))]
    [Migration("20251002091152_RefinedOrderEnumsType")]
    partial class RefinedOrderEnumsType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PasabuyAPI.Models.DeliveryDetails", b =>
                {
                    b.Property<long>("DeliveryIdPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeliveryIdPk"));

                    b.Property<DateTime?>("ActualDeliveryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ActualDistance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CourierLatitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CourierLongitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CustomerLatitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CustomerLongitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric");

                    b.Property<string>("DeliveryNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EstimatedDeliveryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedDistance")
                        .HasColumnType("numeric");

                    b.Property<long?>("OrderIdPK")
                        .HasColumnType("bigint");

                    b.HasKey("DeliveryIdPk");

                    b.HasIndex("OrderIdPK")
                        .IsUnique();

                    b.ToTable("DeliveryDetails");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Orders", b =>
                {
                    b.Property<long>("OrderIdPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderIdPK"));

                    b.Property<long?>("CourierId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderIdPK");

                    b.HasIndex("CourierId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Users", b =>
                {
                    b.Property<long>("UserIdPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserIdPK"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("decimal(2,1)");

                    b.Property<long>("TotalDeliveries")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("YearLevel")
                        .HasColumnType("integer");

                    b.HasKey("UserIdPK");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PasabuyAPI.Models.DeliveryDetails", b =>
                {
                    b.HasOne("PasabuyAPI.Models.Orders", "Order")
                        .WithOne("DeliveryDetails")
                        .HasForeignKey("PasabuyAPI.Models.DeliveryDetails", "OrderIdPK");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Orders", b =>
                {
                    b.HasOne("PasabuyAPI.Models.Users", "Courier")
                        .WithMany("CourierOrders")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PasabuyAPI.Models.Users", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Courier");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Orders", b =>
                {
                    b.Navigation("DeliveryDetails");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Users", b =>
                {
                    b.Navigation("CourierOrders");

                    b.Navigation("CustomerOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
