// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PasabuyAPI.Data;

#nullable disable

namespace PasabuyAPI.Migrations
{
    [DbContext(typeof(PasabuyDbContext))]
    [Migration("20251018072322_RemovedIsActive")]
    partial class RemovedIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PasabuyAPI.Models.ChatMessages", b =>
                {
                    b.Property<long>("MessageIdPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageIdPK"));

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ReceiverIdFK")
                        .HasColumnType("bigint");

                    b.Property<long>("RoomIdFK")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderIdFK")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageIdPK");

                    b.HasIndex("ReceiverIdFK");

                    b.HasIndex("RoomIdFK");

                    b.HasIndex("SenderIdFK");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("PasabuyAPI.Models.ChatRooms", b =>
                {
                    b.Property<long>("RoomIdPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoomIdPK"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("OrderIdFK")
                        .HasColumnType("bigint");

                    b.HasKey("RoomIdPK");

                    b.HasIndex("OrderIdFK")
                        .IsUnique();

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("PasabuyAPI.Models.DeliveryDetails", b =>
                {
                    b.Property<long>("DeliveryIdPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeliveryIdPk"));

                    b.Property<DateTime?>("ActualDeliveryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ActualDistance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ActualPickupTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CourierLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("CourierLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("CustomerLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("CustomerLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("DeliveryNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EstimatedDeliveryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LocationLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("LocationLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<long>("OrderIdFK")
                        .HasColumnType("bigint");

                    b.HasKey("DeliveryIdPk");

                    b.HasIndex("OrderIdFK")
                        .IsUnique();

                    b.ToTable("DeliveryDetails");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Orders", b =>
                {
                    b.Property<long>("OrderIdPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderIdPK"));

                    b.Property<long?>("CourierId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderIdPK");

                    b.HasIndex("CourierId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Payments", b =>
                {
                    b.Property<long>("PaymentIdPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PaymentIdPK"));

                    b.Property<decimal>("BaseFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsItemsFeeConfirmed")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ItemsFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("OrderIdFK")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ProposedItemsFee")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TipAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("UrgencyFee")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PaymentIdPK");

                    b.HasIndex("OrderIdFK")
                        .IsUnique();

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Users", b =>
                {
                    b.Property<long>("UserIdPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserIdPK"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("decimal(2,1)");

                    b.Property<long>("TotalDeliveries")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalOrders")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserIdPK");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PasabuyAPI.Models.VerificationInfo", b =>
                {
                    b.Property<long>("VerifiactionInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VerifiactionInfoId"));

                    b.Property<string>("BackIdPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrontIdPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsurancePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserIdFK")
                        .HasColumnType("bigint");

                    b.Property<string>("VerificationInfoStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VerifiactionInfoId");

                    b.HasIndex("UserIdFK")
                        .IsUnique();

                    b.ToTable("VerificationInfo");
                });

            modelBuilder.Entity("PasabuyAPI.Models.ChatMessages", b =>
                {
                    b.HasOne("PasabuyAPI.Models.Users", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverIdFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasabuyAPI.Models.ChatRooms", "ChatRoom")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RoomIdFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasabuyAPI.Models.Users", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderIdFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PasabuyAPI.Models.ChatRooms", b =>
                {
                    b.HasOne("PasabuyAPI.Models.Orders", "Order")
                        .WithOne("ChatRoom")
                        .HasForeignKey("PasabuyAPI.Models.ChatRooms", "OrderIdFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PasabuyAPI.Models.DeliveryDetails", b =>
                {
                    b.HasOne("PasabuyAPI.Models.Orders", "Order")
                        .WithOne("DeliveryDetails")
                        .HasForeignKey("PasabuyAPI.Models.DeliveryDetails", "OrderIdFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Orders", b =>
                {
                    b.HasOne("PasabuyAPI.Models.Users", "Courier")
                        .WithMany("CourierOrders")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PasabuyAPI.Models.Users", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Courier");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Payments", b =>
                {
                    b.HasOne("PasabuyAPI.Models.Orders", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("PasabuyAPI.Models.Payments", "OrderIdFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PasabuyAPI.Models.VerificationInfo", b =>
                {
                    b.HasOne("PasabuyAPI.Models.Users", "User")
                        .WithOne("VerificationInfo")
                        .HasForeignKey("PasabuyAPI.Models.VerificationInfo", "UserIdFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PasabuyAPI.Models.ChatRooms", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("PasabuyAPI.Models.Orders", b =>
                {
                    b.Navigation("ChatRoom")
                        .IsRequired();

                    b.Navigation("DeliveryDetails")
                        .IsRequired();

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("PasabuyAPI.Models.Users", b =>
                {
                    b.Navigation("CourierOrders");

                    b.Navigation("CustomerOrders");

                    b.Navigation("VerificationInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
